//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilStationMVC.Views.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OilStationMVC.Views.Shared.Resources.ModelResources", typeof(ModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Is Required.
        /// </summary>
        public static string Amount_Is_Required {
            get {
                return ResourceManager.GetString("Amount Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaTransport.
        /// </summary>
        public static string AreaTransport {
            get {
                return ResourceManager.GetString("AreaTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaTransport Amount.
        /// </summary>
        public static string AreaTransport_Amount {
            get {
                return ResourceManager.GetString("AreaTransport Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaTransport Amount Is Required.
        /// </summary>
        public static string AreaTransport_Amount_Is_Required {
            get {
                return ResourceManager.GetString("AreaTransport Amount Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaTransport Is Required.
        /// </summary>
        public static string AreaTransport_Is_Required {
            get {
                return ResourceManager.GetString("AreaTransport Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaTransport Unit.
        /// </summary>
        public static string AreaTransport_Unit {
            get {
                return ResourceManager.GetString("AreaTransport Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaTransport Unit Is Required.
        /// </summary>
        public static string AreaTransport_Unit_Is_Required {
            get {
                return ResourceManager.GetString("AreaTransport Unit Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Unit Price.
        /// </summary>
        public static string Buy_Unit_Price {
            get {
                return ResourceManager.GetString("Buy Unit Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Unit Price Is Required.
        /// </summary>
        public static string Buy_Unit_Price_Is_Required {
            get {
                return ResourceManager.GetString("Buy Unit Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Id.
        /// </summary>
        public static string Car_Id {
            get {
                return ResourceManager.GetString("Car Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Is Required.
        /// </summary>
        public static string Car_Is_Required {
            get {
                return ResourceManager.GetString("Car Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Name.
        /// </summary>
        public static string Car_Name {
            get {
                return ResourceManager.GetString("Car Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Name Is Required.
        /// </summary>
        public static string Car_Name_Is_Required {
            get {
                return ResourceManager.GetString("Car Name Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Area.
        /// </summary>
        public static string Charge_Area {
            get {
                return ResourceManager.GetString("Charge Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Area Is Required.
        /// </summary>
        public static string Charge_Area_Is_Required {
            get {
                return ResourceManager.GetString("Charge Area Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Customer.
        /// </summary>
        public static string Charge_Customer {
            get {
                return ResourceManager.GetString("Charge Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Customer Is Required.
        /// </summary>
        public static string Charge_Customer_Is_Required {
            get {
                return ResourceManager.GetString("Charge Customer Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Is Required.
        /// </summary>
        public static string Company_Is_Required {
            get {
                return ResourceManager.GetString("Company Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string Cost_Center {
            get {
                return ResourceManager.GetString("Cost Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center Is Required.
        /// </summary>
        public static string Cost_Center_Is_Required {
            get {
                return ResourceManager.GetString("Cost Center Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        public static string Current_Balance {
            get {
                return ResourceManager.GetString("Current Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custody Type.
        /// </summary>
        public static string Custody_Type {
            get {
                return ResourceManager.GetString("Custody Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custody Type Is Required.
        /// </summary>
        public static string Custody_Type_Is_Required {
            get {
                return ResourceManager.GetString("Custody Type Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Adress.
        /// </summary>
        public static string Customer_Adress {
            get {
                return ResourceManager.GetString("Customer Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Fee.
        /// </summary>
        public static string Customer_Fee {
            get {
                return ResourceManager.GetString("Customer Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Is Required.
        /// </summary>
        public static string Customer_Is_Required {
            get {
                return ResourceManager.GetString("Customer Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string Customer_Name {
            get {
                return ResourceManager.GetString("Customer Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name Is Required.
        /// </summary>
        public static string Customer_Name_Is_Required {
            get {
                return ResourceManager.GetString("Customer Name Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Qty.
        /// </summary>
        public static string Customer_Qty {
            get {
                return ResourceManager.GetString("Customer Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Qty Is Required.
        /// </summary>
        public static string Customer_Qty_Is_Required {
            get {
                return ResourceManager.GetString("Customer Qty Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Qty Price.
        /// </summary>
        public static string Customer_Qty_Price {
            get {
                return ResourceManager.GetString("Customer Qty Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Qty Price Is Required.
        /// </summary>
        public static string Customer_Qty_Price_Is_Required {
            get {
                return ResourceManager.GetString("Customer Qty Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Total Price.
        /// </summary>
        public static string Customer_Total_Price {
            get {
                return ResourceManager.GetString("Customer Total Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Total Price Is Required.
        /// </summary>
        public static string Customer_Total_Price_Is_Required {
            get {
                return ResourceManager.GetString("Customer Total Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string Customer_Type {
            get {
                return ResourceManager.GetString("Customer Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type Is Required.
        /// </summary>
        public static string Customer_Type_Is_Required {
            get {
                return ResourceManager.GetString("Customer Type Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Unit Price.
        /// </summary>
        public static string Customer_Unit_Price {
            get {
                return ResourceManager.GetString("Customer Unit Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Unit Price Is Required.
        /// </summary>
        public static string Customer_Unit_Price_Is_Required {
            get {
                return ResourceManager.GetString("Customer Unit Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Is Required.
        /// </summary>
        public static string Date_Is_Required {
            get {
                return ResourceManager.GetString("Date Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit No.
        /// </summary>
        public static string Deposit_No {
            get {
                return ResourceManager.GetString("Deposit No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit No Is Required.
        /// </summary>
        public static string Deposit_No_Is_Required {
            get {
                return ResourceManager.GetString("Deposit No Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Is Required.
        /// </summary>
        public static string Driver_Is_Required {
            get {
                return ResourceManager.GetString("Driver Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Name.
        /// </summary>
        public static string Driver_Name {
            get {
                return ResourceManager.GetString("Driver Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Is Required.
        /// </summary>
        public static string Email_Is_Required {
            get {
                return ResourceManager.GetString("Email Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string English_Name {
            get {
                return ResourceManager.GetString("English Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Period Balance.
        /// </summary>
        public static string First_Period_Balance {
            get {
                return ResourceManager.GetString("First Period Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Period Balance Is Required.
        /// </summary>
        public static string First_Period_Balance_Is_Required {
            get {
                return ResourceManager.GetString("First Period Balance Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name Is Required.
        /// </summary>
        public static string Full_Name_Is_Required {
            get {
                return ResourceManager.GetString("Full Name Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innvoice No.
        /// </summary>
        public static string Innvoice_No {
            get {
                return ResourceManager.GetString("Innvoice No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innvoice No Is Required.
        /// </summary>
        public static string Innvoice_No_Is_Required {
            get {
                return ResourceManager.GetString("Innvoice No Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Target Price; Max 18 digits.
        /// </summary>
        public static string Invalid_Target_Price__Max_18_digits {
            get {
                return ResourceManager.GetString("Invalid Target Price; Max 18 digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Target Price; Maximum Two Decimal Points..
        /// </summary>
        public static string Invalid_Target_Price__Maximum_Two_Decimal_Points_ {
            get {
                return ResourceManager.GetString("Invalid Target Price; Maximum Two Decimal Points.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Be Email Aderess.
        /// </summary>
        public static string Must_Be_Email_Aderess {
            get {
                return ResourceManager.GetString("Must Be Email Aderess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Be Email Adress.
        /// </summary>
        public static string Must_Be_Email_Adress {
            get {
                return ResourceManager.GetString("Must Be Email Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Be Phone Number.
        /// </summary>
        public static string Must_Be_Phone_Number {
            get {
                return ResourceManager.GetString("Must Be Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Is Required.
        /// </summary>
        public static string Name_Is_Required {
            get {
                return ResourceManager.GetString("Name Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil80 QTY.
        /// </summary>
        public static string Oil80_QTY {
            get {
                return ResourceManager.GetString("Oil80 QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil80 QTY Is Required.
        /// </summary>
        public static string Oil80_QTY_Is_Required {
            get {
                return ResourceManager.GetString("Oil80 QTY Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil80 Total Price.
        /// </summary>
        public static string Oil80_Total_Price {
            get {
                return ResourceManager.GetString("Oil80 Total Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil80 Total Price Is Required.
        /// </summary>
        public static string Oil80_Total_Price_Is_Required {
            get {
                return ResourceManager.GetString("Oil80 Total Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil80 Unit Price.
        /// </summary>
        public static string Oil80_Unit_Price {
            get {
                return ResourceManager.GetString("Oil80 Unit Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil80 Unit Price Is Required.
        /// </summary>
        public static string Oil80_Unit_Price_Is_Required {
            get {
                return ResourceManager.GetString("Oil80 Unit Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil92 QTY.
        /// </summary>
        public static string Oil92_QTY {
            get {
                return ResourceManager.GetString("Oil92 QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil92 QTY Is Required.
        /// </summary>
        public static string Oil92_QTY_Is_Required {
            get {
                return ResourceManager.GetString("Oil92 QTY Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil92 Total Price.
        /// </summary>
        public static string Oil92_Total_Price {
            get {
                return ResourceManager.GetString("Oil92 Total Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil92 Total Price Is Required.
        /// </summary>
        public static string Oil92_Total_Price_Is_Required {
            get {
                return ResourceManager.GetString("Oil92 Total Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil92 Unit Price.
        /// </summary>
        public static string Oil92_Unit_Price {
            get {
                return ResourceManager.GetString("Oil92 Unit Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil92 Unit Price Is Required.
        /// </summary>
        public static string Oil92_Unit_Price_Is_Required {
            get {
                return ResourceManager.GetString("Oil92 Unit Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil95 QTY.
        /// </summary>
        public static string Oil95_QTY {
            get {
                return ResourceManager.GetString("Oil95 QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil95 QTY Is Required.
        /// </summary>
        public static string Oil95_QTY_Is_Required {
            get {
                return ResourceManager.GetString("Oil95 QTY Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil95 Total Price.
        /// </summary>
        public static string Oil95_Total_Price {
            get {
                return ResourceManager.GetString("Oil95 Total Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil95 Total Price Is Required.
        /// </summary>
        public static string Oil95_Total_Price_Is_Required {
            get {
                return ResourceManager.GetString("Oil95 Total Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil95 Unit Price.
        /// </summary>
        public static string Oil95_Unit_Price {
            get {
                return ResourceManager.GetString("Oil95 Unit Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil95 Unit Price Is Required.
        /// </summary>
        public static string Oil95_Unit_Price_Is_Required {
            get {
                return ResourceManager.GetString("Oil95 Unit Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance.
        /// </summary>
        public static string Opening_Balance {
            get {
                return ResourceManager.GetString("Opening Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance Date.
        /// </summary>
        public static string Opening_Balance_Date {
            get {
                return ResourceManager.GetString("Opening Balance Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance Date Is Required.
        /// </summary>
        public static string Opening_Balance_Date_Is_Required {
            get {
                return ResourceManager.GetString("Opening Balance Date Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance Is Required.
        /// </summary>
        public static string Opening_Balance_Is_Required {
            get {
                return ResourceManager.GetString("Opening Balance Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance State.
        /// </summary>
        public static string Opening_Balance_State {
            get {
                return ResourceManager.GetString("Opening Balance State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance State Is Required.
        /// </summary>
        public static string Opening_Balance_State_Is_Required {
            get {
                return ResourceManager.GetString("Opening Balance State Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Is Required.
        /// </summary>
        public static string Password_Is_Required {
            get {
                return ResourceManager.GetString("Password Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Is Required.
        /// </summary>
        public static string Phone_Number_Is_Required {
            get {
                return ResourceManager.GetString("Phone Number Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Is Required.
        /// </summary>
        public static string Qty_Is_Required {
            get {
                return ResourceManager.GetString("Qty Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Price.
        /// </summary>
        public static string Qty_Price {
            get {
                return ResourceManager.GetString("Qty Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Price Is Required.
        /// </summary>
        public static string Qty_Price_Is_Required {
            get {
                return ResourceManager.GetString("Qty Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Remember_me_ {
            get {
                return ResourceManager.GetString("Remember me?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Person.
        /// </summary>
        public static string Responsible_Person {
            get {
                return ResourceManager.GetString("Responsible Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Person Is Required.
        /// </summary>
        public static string Responsible_Person_Is_Required {
            get {
                return ResourceManager.GetString("Responsible Person Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Unit Price.
        /// </summary>
        public static string Sale_Unit_Price {
            get {
                return ResourceManager.GetString("Sale Unit Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Unit Price Is Required.
        /// </summary>
        public static string Sale_Unit_Price_Is_Required {
            get {
                return ResourceManager.GetString("Sale Unit Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar QTY.
        /// </summary>
        public static string Solar_QTY {
            get {
                return ResourceManager.GetString("Solar QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar QTY Is Required.
        /// </summary>
        public static string Solar_QTY_Is_Required {
            get {
                return ResourceManager.GetString("Solar QTY Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Total Price.
        /// </summary>
        public static string Solar_Total_Price {
            get {
                return ResourceManager.GetString("Solar Total Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Total Price Is Required.
        /// </summary>
        public static string Solar_Total_Price_Is_Required {
            get {
                return ResourceManager.GetString("Solar Total Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Unit Price.
        /// </summary>
        public static string Solar_Unit_Price {
            get {
                return ResourceManager.GetString("Solar Unit Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Unit Price Is Required.
        /// </summary>
        public static string Solar_Unit_Price_Is_Required {
            get {
                return ResourceManager.GetString("Solar Unit Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staion.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Is Required.
        /// </summary>
        public static string Station_Is_Required {
            get {
                return ResourceManager.GetString("Station Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Id.
        /// </summary>
        public static string Stock_Id {
            get {
                return ResourceManager.GetString("Stock Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Name.
        /// </summary>
        public static string Stock_Name {
            get {
                return ResourceManager.GetString("Stock Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Name English.
        /// </summary>
        public static string Stock_Name_English {
            get {
                return ResourceManager.GetString("Stock Name English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Name Is Required.
        /// </summary>
        public static string Stock_Name_Is_Required {
            get {
                return ResourceManager.GetString("Stock Name Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Transport Amount.
        /// </summary>
        public static string Stock_Transport_Amount {
            get {
                return ResourceManager.GetString("Stock Transport Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Transport Amount Is Required.
        /// </summary>
        public static string Stock_Transport_Amount_Is_Required {
            get {
                return ResourceManager.GetString("Stock Transport Amount Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Transport Unit.
        /// </summary>
        public static string Stock_Transport_Unit {
            get {
                return ResourceManager.GetString("Stock Transport Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Transport Unit Is Required.
        /// </summary>
        public static string Stock_Transport_Unit_Is_Required {
            get {
                return ResourceManager.GetString("Stock Transport Unit Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Unit Cost.
        /// </summary>
        public static string Stock_Unit_Cost {
            get {
                return ResourceManager.GetString("Stock Unit Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Unit Cost Is Required.
        /// </summary>
        public static string Stock_Unit_Cost_Is_Required {
            get {
                return ResourceManager.GetString("Stock Unit Cost Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Is Required.
        /// </summary>
        public static string Telephone_Is_Required {
            get {
                return ResourceManager.GetString("Telephone Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string Total_Price {
            get {
                return ResourceManager.GetString("Total Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price Is Required.
        /// </summary>
        public static string Total_Price_Is_Required {
            get {
                return ResourceManager.GetString("Total Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string Unit_Cost {
            get {
                return ResourceManager.GetString("Unit Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Unit_Price {
            get {
                return ResourceManager.GetString("Unit Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price Is Required.
        /// </summary>
        public static string Unit_Price_Is_Required {
            get {
                return ResourceManager.GetString("Unit Price Is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unti Cost Is Required.
        /// </summary>
        public static string Unti_Cost_Is_Required {
            get {
                return ResourceManager.GetString("Unti Cost Is Required", resourceCulture);
            }
        }
    }
}
