//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilStationMVC.Views.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OilStationMVC.Views.Shared.Resources.SiteResource", typeof(SiteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure To Delete.
        /// </summary>
        public static string Are_You_Sure_To_Delete {
            get {
                return ResourceManager.GetString("Are You Sure To Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Transport List.
        /// </summary>
        public static string Area_Transport_List {
            get {
                return ResourceManager.GetString("Area Transport List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string Back_To_List {
            get {
                return ResourceManager.GetString("Back To List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balalnce.
        /// </summary>
        public static string Balalnce {
            get {
                return ResourceManager.GetString("Balalnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Unit Price.
        /// </summary>
        public static string Buy_Unit_Price {
            get {
                return ResourceManager.GetString("Buy Unit Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Custody List.
        /// </summary>
        public static string Car_Custody_List {
            get {
                return ResourceManager.GetString("Car Custody List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Id.
        /// </summary>
        public static string Car_Id {
            get {
                return ResourceManager.GetString("Car Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Name.
        /// </summary>
        public static string Car_Name {
            get {
                return ResourceManager.GetString("Car Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars Dashboard.
        /// </summary>
        public static string Cars_Dashboard {
            get {
                return ResourceManager.GetString("Cars Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars List.
        /// </summary>
        public static string Cars_List {
            get {
                return ResourceManager.GetString("Cars List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash From Box List.
        /// </summary>
        public static string Cash_From_Box_List {
            get {
                return ResourceManager.GetString("Cash From Box List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashing List.
        /// </summary>
        public static string Cashing_List {
            get {
                return ResourceManager.GetString("Cashing List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Area.
        /// </summary>
        public static string Charge_Area {
            get {
                return ResourceManager.GetString("Charge Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Areas List.
        /// </summary>
        public static string Charge_Areas_List {
            get {
                return ResourceManager.GetString("Charge Areas List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Customer.
        /// </summary>
        public static string Charge_Customer {
            get {
                return ResourceManager.GetString("Charge Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies Dashboard.
        /// </summary>
        public static string Companies_Dashboard {
            get {
                return ResourceManager.GetString("Companies Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies List.
        /// </summary>
        public static string Companies_List {
            get {
                return ResourceManager.GetString("Companies List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Invoices VS Company Deposits.
        /// </summary>
        public static string CompanyInvoicesVSCompanyDepositbarChart {
            get {
                return ResourceManager.GetString("CompanyInvoicesVSCompanyDepositbarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string Cost_Center {
            get {
                return ResourceManager.GetString("Cost Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Create_New {
            get {
                return ResourceManager.GetString("Create New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Area Transport.
        /// </summary>
        public static string Create_New_Area_Transport {
            get {
                return ResourceManager.GetString("Create New Area Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Car.
        /// </summary>
        public static string Create_New_Car {
            get {
                return ResourceManager.GetString("Create New Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Car Custody.
        /// </summary>
        public static string Create_New_Car_Custody {
            get {
                return ResourceManager.GetString("Create New Car Custody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Cash From Box.
        /// </summary>
        public static string Create_New_Cash_From_Box {
            get {
                return ResourceManager.GetString("Create New Cash From Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Cashing.
        /// </summary>
        public static string Create_New_Cashing {
            get {
                return ResourceManager.GetString("Create New Cashing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Charge Area.
        /// </summary>
        public static string Create_New_Charge_Area {
            get {
                return ResourceManager.GetString("Create New Charge Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Company.
        /// </summary>
        public static string Create_New_Company {
            get {
                return ResourceManager.GetString("Create New Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Company Invoice.
        /// </summary>
        public static string Create_New_Company_Invoice {
            get {
                return ResourceManager.GetString("Create New Company Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Custody Type.
        /// </summary>
        public static string Create_New_Custody_Type {
            get {
                return ResourceManager.GetString("Create New Custody Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Customer.
        /// </summary>
        public static string Create_New_Customer {
            get {
                return ResourceManager.GetString("Create New Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Customer Invoice.
        /// </summary>
        public static string Create_New_Customer_Invoice {
            get {
                return ResourceManager.GetString("Create New Customer Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Deposit In Box.
        /// </summary>
        public static string Create_New_Deposit_In_Box {
            get {
                return ResourceManager.GetString("Create New Deposit In Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Driver.
        /// </summary>
        public static string Create_New_Driver {
            get {
                return ResourceManager.GetString("Create New Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Expense Type.
        /// </summary>
        public static string Create_New_Expense_Type {
            get {
                return ResourceManager.GetString("Create New Expense Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Expenses.
        /// </summary>
        public static string Create_New_Expenses {
            get {
                return ResourceManager.GetString("Create New Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Mazot Bank Deposit.
        /// </summary>
        public static string Create_New_Mazot_Bank_Deposit {
            get {
                return ResourceManager.GetString("Create New Mazot Bank Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Mazot Customer Invoice.
        /// </summary>
        public static string Create_New_Mazot_Customer_Invoice {
            get {
                return ResourceManager.GetString("Create New Mazot Customer Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Mazot Invoice.
        /// </summary>
        public static string Create_New_Mazot_Invoice {
            get {
                return ResourceManager.GetString("Create New Mazot Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Product.
        /// </summary>
        public static string Create_New_Product {
            get {
                return ResourceManager.GetString("Create New Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Station.
        /// </summary>
        public static string Create_New_Station {
            get {
                return ResourceManager.GetString("Create New Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Station Deposit.
        /// </summary>
        public static string Create_New_Station_Deposit {
            get {
                return ResourceManager.GetString("Create New Station Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Stock.
        /// </summary>
        public static string Create_New_Stock {
            get {
                return ResourceManager.GetString("Create New Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Voucher.
        /// </summary>
        public static string Create_New_Voucher {
            get {
                return ResourceManager.GetString("Create New Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        public static string Current_Balance {
            get {
                return ResourceManager.GetString("Current Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custody Type List.
        /// </summary>
        public static string Custody_Type_List {
            get {
                return ResourceManager.GetString("Custody Type List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Invoices List.
        /// </summary>
        public static string Customer_Invoices_List {
            get {
                return ResourceManager.GetString("Customer Invoices List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string Customer_Type {
            get {
                return ResourceManager.GetString("Customer Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers Dashboard.
        /// </summary>
        public static string Customers_Dashboard {
            get {
                return ResourceManager.GetString("Customers Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers List.
        /// </summary>
        public static string Customers_List {
            get {
                return ResourceManager.GetString("Customers List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        public static string Dashboards {
            get {
                return ResourceManager.GetString("Dashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        public static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Car.
        /// </summary>
        public static string Delete_Car {
            get {
                return ResourceManager.GetString("Delete Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Custody Type.
        /// </summary>
        public static string Delete_Custody_Type {
            get {
                return ResourceManager.GetString("Delete Custody Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Expense Type.
        /// </summary>
        public static string Delete_Expense_Type {
            get {
                return ResourceManager.GetString("Delete Expense Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit In Box List.
        /// </summary>
        public static string Deposit_In_Box_List {
            get {
                return ResourceManager.GetString("Deposit In Box List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit No.
        /// </summary>
        public static string Deposit_No {
            get {
                return ResourceManager.GetString("Deposit No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Name.
        /// </summary>
        public static string Driver_Name {
            get {
                return ResourceManager.GetString("Driver Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers List.
        /// </summary>
        public static string Drivers_List {
            get {
                return ResourceManager.GetString("Drivers List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edittt.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Area Transport Data.
        /// </summary>
        public static string Edit_Area_Transport_Data {
            get {
                return ResourceManager.GetString("Edit Area Transport Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Car Custody.
        /// </summary>
        public static string Edit_Car_Custody {
            get {
                return ResourceManager.GetString("Edit Car Custody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Car Data.
        /// </summary>
        public static string Edit_Car_Data {
            get {
                return ResourceManager.GetString("Edit Car Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cash From Box.
        /// </summary>
        public static string Edit_Cash_From_Box {
            get {
                return ResourceManager.GetString("Edit Cash From Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cashing.
        /// </summary>
        public static string Edit_Cashing {
            get {
                return ResourceManager.GetString("Edit Cashing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Charge Area Data.
        /// </summary>
        public static string Edit_Charge_Area_Data {
            get {
                return ResourceManager.GetString("Edit Charge Area Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Company Data.
        /// </summary>
        public static string Edit_Company_Data {
            get {
                return ResourceManager.GetString("Edit Company Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Company Invoice.
        /// </summary>
        public static string Edit_Company_Invoice {
            get {
                return ResourceManager.GetString("Edit Company Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Custody Type.
        /// </summary>
        public static string Edit_Custody_Type {
            get {
                return ResourceManager.GetString("Edit Custody Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer Data.
        /// </summary>
        public static string Edit_Customer_Data {
            get {
                return ResourceManager.GetString("Edit Customer Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer Invoice.
        /// </summary>
        public static string Edit_Customer_Invoice {
            get {
                return ResourceManager.GetString("Edit Customer Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Deposit In Box.
        /// </summary>
        public static string Edit_Deposit_In_Box {
            get {
                return ResourceManager.GetString("Edit Deposit In Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Driver Data.
        /// </summary>
        public static string Edit_Driver_Data {
            get {
                return ResourceManager.GetString("Edit Driver Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Expense Type.
        /// </summary>
        public static string Edit_Expense_Type {
            get {
                return ResourceManager.GetString("Edit Expense Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Expenses.
        /// </summary>
        public static string Edit_Expenses {
            get {
                return ResourceManager.GetString("Edit Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Mazot Bank Deposit.
        /// </summary>
        public static string Edit_Mazot_Bank_Deposit {
            get {
                return ResourceManager.GetString("Edit Mazot Bank Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Mazot Customer Invoice.
        /// </summary>
        public static string Edit_Mazot_Customer_Invoice {
            get {
                return ResourceManager.GetString("Edit Mazot Customer Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Mazot Invoice.
        /// </summary>
        public static string Edit_Mazot_Invoice {
            get {
                return ResourceManager.GetString("Edit Mazot Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product Data.
        /// </summary>
        public static string Edit_Product_Data {
            get {
                return ResourceManager.GetString("Edit Product Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Station Data.
        /// </summary>
        public static string Edit_Station_Data {
            get {
                return ResourceManager.GetString("Edit Station Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Station Deposit.
        /// </summary>
        public static string Edit_Station_Deposit {
            get {
                return ResourceManager.GetString("Edit Station Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Stock Data.
        /// </summary>
        public static string Edit_Stock_Data {
            get {
                return ResourceManager.GetString("Edit Stock Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Voucher.
        /// </summary>
        public static string Edit_Voucher {
            get {
                return ResourceManager.GetString("Edit Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses List.
        /// </summary>
        public static string Expenses_List {
            get {
                return ResourceManager.GetString("Expenses List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Type List.
        /// </summary>
        public static string Expenses_Type_List {
            get {
                return ResourceManager.GetString("Expenses Type List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Details.
        /// </summary>
        public static string Go_To_Details {
            get {
                return ResourceManager.GetString("Go To Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Login Page.
        /// </summary>
        public static string Go_To_Login_Page {
            get {
                return ResourceManager.GetString("Go To Login Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the terms.
        /// </summary>
        public static string I_agree_to_the_terms {
            get {
                return ResourceManager.GetString("I agree to the terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot my password.
        /// </summary>
        public static string I_forgot_my_password {
            get {
                return ResourceManager.GetString("I forgot my password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices List.
        /// </summary>
        public static string Invoices_List {
            get {
                return ResourceManager.GetString("Invoices List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string Journal_Type {
            get {
                return ResourceManager.GetString("Journal Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mazot Bank Deposit List.
        /// </summary>
        public static string Mazot_Bank_Deposit_List {
            get {
                return ResourceManager.GetString("Mazot Bank Deposit List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mazot Customer Invoice List.
        /// </summary>
        public static string Mazot_Customer_Invoice_List {
            get {
                return ResourceManager.GetString("Mazot Customer Invoice List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mazot Invoice List.
        /// </summary>
        public static string Mazot_Invoice_List {
            get {
                return ResourceManager.GetString("Mazot Invoice List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mazot Invoices VS Deposits.
        /// </summary>
        public static string MazotInvoicesVSDepositbarChart {
            get {
                return ResourceManager.GetString("MazotInvoicesVSDepositbarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance.
        /// </summary>
        public static string Opening_Balance {
            get {
                return ResourceManager.GetString("Opening Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance Date.
        /// </summary>
        public static string Opening_Balance_Date {
            get {
                return ResourceManager.GetString("Opening Balance Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance State.
        /// </summary>
        public static string Opening_Balance_State {
            get {
                return ResourceManager.GetString("Opening Balance State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Verification Code.
        /// </summary>
        public static string Please_Enter_Verification_Code {
            get {
                return ResourceManager.GetString("Please Enter Verification Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select....
        /// </summary>
        public static string Please_Select {
            get {
                return ResourceManager.GetString("Please Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Balance.
        /// </summary>
        public static string Products_Balance {
            get {
                return ResourceManager.GetString("Products Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products List.
        /// </summary>
        public static string Products_List {
            get {
                return ResourceManager.GetString("Products List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new membership.
        /// </summary>
        public static string Register_a_new_membership {
            get {
                return ResourceManager.GetString("Register a new membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Remember_me_ {
            get {
                return ResourceManager.GetString("Remember me?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request new password.
        /// </summary>
        public static string Request_new_password {
            get {
                return ResourceManager.GetString("Request new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Password.
        /// </summary>
        public static string Reset_Your_Password {
            get {
                return ResourceManager.GetString("Reset Your Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Person.
        /// </summary>
        public static string Responsible_Person {
            get {
                return ResourceManager.GetString("Responsible Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Unit Price.
        /// </summary>
        public static string Sale_Unit_Price {
            get {
                return ResourceManager.GetString("Sale Unit Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Two Factor Authentication.
        /// </summary>
        public static string Select_Two_Factor_Authentication {
            get {
                return ResourceManager.GetString("Select Two Factor Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Code.
        /// </summary>
        public static string Send_Code {
            get {
                return ResourceManager.GetString("Send Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Sign_In {
            get {
                return ResourceManager.GetString("Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to start your session.
        /// </summary>
        public static string Sign_in_to_start_your_session {
            get {
                return ResourceManager.GetString("Sign in to start your session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staion.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Deposit List.
        /// </summary>
        public static string Station_Deposit_List {
            get {
                return ResourceManager.GetString("Station Deposit List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations  List.
        /// </summary>
        public static string Stations__List {
            get {
                return ResourceManager.GetString("Stations  List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Details.
        /// </summary>
        public static string Stock_Details {
            get {
                return ResourceManager.GetString("Stock Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Id.
        /// </summary>
        public static string Stock_Id {
            get {
                return ResourceManager.GetString("Stock Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock List.
        /// </summary>
        public static string Stock_List {
            get {
                return ResourceManager.GetString("Stock List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Name.
        /// </summary>
        public static string Stock_Name {
            get {
                return ResourceManager.GetString("Stock Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Unit Cost.
        /// </summary>
        public static string Stock_Unit_Cost {
            get {
                return ResourceManager.GetString("Stock Unit Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Customers Credit.
        /// </summary>
        public static string Total_Customers_Credit {
            get {
                return ResourceManager.GetString("Total Customers Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Customers Debit.
        /// </summary>
        public static string Total_Customers_Debit {
            get {
                return ResourceManager.GetString("Total Customers Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Customers Final Balance.
        /// </summary>
        public static string Total_Customers_Final_Balance {
            get {
                return ResourceManager.GetString("Total Customers Final Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string Total_Price {
            get {
                return ResourceManager.GetString("Total Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unti Cost.
        /// </summary>
        public static string Unit_Cost {
            get {
                return ResourceManager.GetString("Unit Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher List.
        /// </summary>
        public static string Voucher_List {
            get {
                return ResourceManager.GetString("Voucher List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Will Send Verification Code Based On Your Selection.
        /// </summary>
        public static string We_Will_Send_Verification_Code_Based_On_Your_Selection {
            get {
                return ResourceManager.GetString("We Will Send Verification Code Based On Your Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are only one step a way from your new password, recover your password now..
        /// </summary>
        public static string You_are_only_one_step_a_way_from_your_new_password__recover_your_password_now_ {
            get {
                return ResourceManager.GetString("You are only one step a way from your new password, recover your password now.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You forgot your password? Here you can easily retrieve a new password..
        /// </summary>
        public static string You_forgot_your_password__Here_you_can_easily_retrieve_a_new_password_ {
            get {
                return ResourceManager.GetString("You forgot your password? Here you can easily retrieve a new password.", resourceCulture);
            }
        }
    }
}
